// Lista de proyectos del portafolio con texto bilingüe (es / en)
export const proyectos = [
  {
    id: 6,
    etiquetas: ["Next.js", "React", "Tailwind CSS"],
    estado: "publicado",
    anio: "2025",
    estrellas: 0,
    bifurcaciones: 0,
    url: "https://github.com/monzay/sea-automotores",
    paginaWeb: "https://seaautomotores.com",
    imagen: "/images-webs/sea_automotores.png",
    destacado: true,
    resaltado: true,
    es: {
      titulo: "SEA Automotores",
      descripcion: "Plataforma digital para concesionaria de vehículos en San Salvador de Jujuy. Catálogo de autos y motos, financiamiento, tasación online, testimonios de clientes y contacto directo por WhatsApp.",
    },
    en: {
      titulo: "SEA Automotores",
      descripcion: "Digital platform for a vehicle dealership in San Salvador de Jujuy. Car and motorcycle catalog, financing options, online appraisal, customer testimonials, and direct WhatsApp contact.",
    },
  },

  {
    id: 7,
    etiquetas: ["Next.js", "React", "Tailwind CSS"],
    estado: "en-progreso",
    anio: "2025",
    estrellas: 0,
    bifurcaciones: 0,
    url: "https://github.com/monzay/controol",
    paginaWeb: "https://controol.vercel.app",
    imagen: "/images-webs/control.png",
    destacado: true,
    resaltado: false,
    es: {
      titulo: "Controol",
      descripcion: "Panel de administración personal. Proyecto experimental para explorar arquitecturas de dashboards modernos.",
    },
    en: {
      titulo: "Controol",
      descripcion: "Personal administration panel. Experimental project to explore modern dashboard architectures.",
    },
  },
  {
    id: 8,
    etiquetas: ["WordPress", "Elementor", "WooCommerce"],
    estado: "publicado",
    anio: "2025",
    estrellas: 0,
    bifurcaciones: 0,
    url: "",
    paginaWeb: "https://jrautomotores.com.ar",
    imagen: "/images-webs/jr_automotores.png",
    destacado: true,
    resaltado: false,
    es: {
      titulo: "JR Automotores",
      descripcion: "Sitio web para concesionaria oficial JAC Motors en Buenos Aires. Catálogo de más de 100 vehículos usados y 0km, búsqueda avanzada por tipo y marca, financiamiento a medida, tasación online y contacto directo por WhatsApp.",
    },
    en: {
      titulo: "JR Automotores",
      descripcion: "Website for official JAC Motors dealership in Buenos Aires. Catalog of 100+ used and new vehicles, advanced search by type and brand, tailored financing, online appraisal, and direct WhatsApp contact.",
    },
  },
  {
    id: 9,
    etiquetas: ["Next.js", "React", "Tailwind CSS"],
    estado: "publicado",
    anio: "2025",
    estrellas: 0,
    bifurcaciones: 0,
    url: "",
    paginaWeb: "https://gigienergyy.vercel.app",
    imagen: "/images-webs/gigi.png",
    destacado: true,
    resaltado: false,
    es: {
      titulo: "GiGi Energy Drink",
      descripcion: "Landing y tienda online para marca de bebidas energéticas saludables. Catálogo de productos, carrito de compras, programa de afiliados, integración con Instagram y diseño orientado a conversión para audiencia joven.",
    },
    en: {
      titulo: "GiGi Energy Drink",
      descripcion: "Landing page and online store for a healthy energy drink brand. Product catalog, shopping cart, affiliate program, Instagram integration, and conversion-focused design targeting a young audience.",
    },
  },
]
