// Lista de proyectos del portafolio con texto bilingüe (es / en)
export const proyectos = [
  {
    id: 0,
    etiquetas: ["Next.js 16", "React", "Tailwind", "JavaScript"],
    estado: "en-progreso",
    anio: "2025",
    estrellas: 12,
    bifurcaciones: 2,
    url: "https://github.com/monzay/portfolio",
    paginaWeb: "https://joelmartinez.dev",
    destacado: true,
    resaltado: true,
    es: {
      titulo: "Portfolio Personal",
      descripcion: "Mi sitio web personal construido con Next.js 16, Tailwind CSS y componentes reutilizables. Incluye modo oscuro, animaciones y diseño responsivo.",
    },
    en: {
      titulo: "Personal Portfolio",
      descripcion: "My personal website built with Next.js 16, Tailwind CSS and reusable components. Includes dark mode, animations, and responsive design.",
    },
  },
  {
    id: 1,
    etiquetas: ["Next.js", "PostgreSQL", "Prisma", "TypeScript"],
    estado: "publicado",
    anio: "2024",
    estrellas: 8,
    bifurcaciones: 3,
    url: "https://github.com/monzay/gestion-app",
    destacado: true,
    es: {
      titulo: "Sistema de Gestión",
      descripcion: "Aplicación web para gestión de inventario y ventas. Incluye dashboard, reportes y sistema de autenticación.",
    },
    en: {
      titulo: "Management System",
      descripcion: "Web application for inventory and sales management. Includes dashboard, reports, and authentication system.",
    },
  },
  {
    id: 2,
    etiquetas: ["JavaScript", "Node.js", "Express", "MongoDB"],
    estado: "publicado",
    anio: "2023",
    estrellas: 15,
    bifurcaciones: 4,
    url: "https://github.com/monzay/node-api",
    destacado: false,
    es: {
      titulo: "API REST Node.js",
      descripcion: "API RESTful construida con Node.js y Express. Incluye autenticación JWT, validación y documentación con Swagger.",
    },
    en: {
      titulo: "Node.js REST API",
      descripcion: "RESTful API built with Node.js and Express. Includes JWT authentication, validation, and Swagger documentation.",
    },
  },
  {
    id: 3,
    etiquetas: ["React", "Redux", "Stripe", "Firebase"],
    estado: "publicado",
    anio: "2024",
    estrellas: 22,
    bifurcaciones: 7,
    url: "https://github.com/monzay/ecommerce-react",
    paginaWeb: "https://tienda-demo.vercel.app",
    destacado: true,
    es: {
      titulo: "E-commerce React",
      descripcion: "Tienda online con carrito de compras, pasarela de pagos y panel de administración.",
    },
    en: {
      titulo: "React E-commerce",
      descripcion: "Online store with shopping cart, payment gateway, and administration panel.",
    },
  },
  {
    id: 4,
    etiquetas: ["TypeScript", "Socket.io", "React", "Node.js"],
    estado: "archivado",
    anio: "2023",
    estrellas: 18,
    bifurcaciones: 5,
    url: "https://github.com/monzay/realtime-chat",
    destacado: false,
    es: {
      titulo: "Chat en Tiempo Real",
      descripcion: "Aplicación de chat con WebSockets, salas de conversación y notificaciones push.",
    },
    en: {
      titulo: "Real-time Chat",
      descripcion: "Chat application with WebSockets, conversation rooms, and push notifications.",
    },
  },
  {
    id: 5,
    etiquetas: ["React", "Recharts", "TanStack Query", "Tailwind"],
    estado: "en-progreso",
    anio: "2025",
    estrellas: 10,
    bifurcaciones: 2,
    url: "https://github.com/monzay/analytics-dashboard",
    destacado: true,
    es: {
      titulo: "Dashboard Analytics",
      descripcion: "Panel de control con gráficos interactivos, métricas en tiempo real y exportación de reportes.",
    },
    en: {
      titulo: "Analytics Dashboard",
      descripcion: "Control panel with interactive charts, real-time metrics, and report exports.",
    },
  },
]
