// Lista de proyectos del portafolio con texto bilingüe (es / en)
export const proyectos = [
  {
    id: 6,
    etiquetas: ["Next.js", "React", "Tailwind CSS"],
    estado: "publicado",
    anio: "2025",
    estrellas: 0,
    bifurcaciones: 0,
    url: "https://github.com/monzay/sea-automotores",
    paginaWeb: "https://seaautomotores.com",
    imagen: "/images-webs/sea_automotores.png",
    destacado: true,
    resaltado: true,
    es: {
      titulo: "SEA Automotores",
      descripcion: "Página web para la agencia SEA Automotores. Catálogo de vehículos, consulta de stock, tasación online y contacto directo con el concesionario.",
    },
    en: {
      titulo: "SEA Automotores",
      descripcion: "Website for SEA Automotores agency. Vehicle catalog, stock inquiry, online appraisal, and direct contact with the dealership.",
    },
  },

  {
    id: 7,
    etiquetas: ["Next.js", "React", "Tailwind CSS"],
    estado: "en-progreso",
    anio: "2025",
    estrellas: 0,
    bifurcaciones: 0,
    url: "https://github.com/monzay/controol",
    paginaWeb: "https://controol.vercel.app",
    imagen: "/images-webs/control.png",
    destacado: true,
    resaltado: false,
    es: {
      titulo: "Controol",
      descripcion: "App web de gestión de hábitos, tareas y metas personales. Panel intuitivo para organizar tu día a día y hacer seguimiento de tu progreso.",
    },
    en: {
      titulo: "Controol",
      descripcion: "Web app for managing habits, tasks, and personal goals. Intuitive dashboard to organize your daily routine and track your progress.",
    },
  },
  {
    id: 8,
    etiquetas: ["WordPress", "Elementor", "WooCommerce"],
    estado: "publicado",
    anio: "2025",
    estrellas: 0,
    bifurcaciones: 0,
    url: "",
    paginaWeb: "https://jrautomotores.com.ar",
    imagen: "/images-webs/jr_automotores.png",
    destacado: true,
    resaltado: false,
    es: {
      titulo: "JR Automotores",
      descripcion: "Sitio web para concesionaria oficial JAC Motors en Buenos Aires. Catálogo de más de 100 vehículos usados y 0km, búsqueda avanzada por tipo y marca, financiamiento a medida, tasación online y contacto directo por WhatsApp.",
    },
    en: {
      titulo: "JR Automotores",
      descripcion: "Website for official JAC Motors dealership in Buenos Aires. Catalog of 100+ used and new vehicles, advanced search by type and brand, tailored financing, online appraisal, and direct WhatsApp contact.",
    },
  },
  {
    id: 9,
    etiquetas: ["Next.js", "React", "Tailwind CSS"],
    estado: "publicado",
    anio: "2025",
    estrellas: 0,
    bifurcaciones: 0,
    url: "",
    paginaWeb: "https://gigienergyy.vercel.app",
    imagen: "/images-webs/gigi.png",
    destacado: true,
    resaltado: false,
    es: {
      titulo: "GiGi Energy Drink",
      descripcion: "Landing page para marca de bebidas energéticas saludables. Diseño moderno orientado a conversión para audiencia joven.",
    },
    en: {
      titulo: "GiGi Energy Drink",
      descripcion: "Landing page for a healthy energy drink brand. Modern conversion-focused design targeting a young audience.",
    },
  },
  {
    id: 10,
    etiquetas: ["Next.js", "React", "Tailwind CSS"],
    estado: "publicado",
    anio: "2025",
    estrellas: 0,
    bifurcaciones: 0,
    url: "",
    paginaWeb: "https://modelo-web-3.vercel.app",
    imagen: "/images-webs/iron_district.png",
    destacado: true,
    resaltado: false,
    es: {
      titulo: "Iron District",
      descripcion: "Modelo de sitio web.",
    },
    en: {
      titulo: "Iron District",
      descripcion: "Website model.",
    },
  },
  {
    id: 11,
    etiquetas: ["Next.js", "React", "Tailwind CSS"],
    estado: "publicado",
    anio: "2025",
    estrellas: 0,
    bifurcaciones: 0,
    url: "",
    paginaWeb: "https://modelo-web-2.vercel.app",
    imagen: "/images-webs/compute.png",
    destacado: true,
    resaltado: false,
    es: {
      titulo: "Compute",
      descripcion: "Modelo de sitio web.",
    },
    en: {
      titulo: "Compute",
      descripcion: "Website model.",
    },
  },
]
