import {
  SiJavascript, SiReact, SiNodedotjs, SiHtml5,
  SiCss, SiExpress, SiMysql, SiSqlite, SiPrisma,
  SiGit, SiGithub, SiPython, SiNextdotjs, SiTailwindcss,
} from "react-icons/si"

// Colores de punto por categoría
export const colorCategoria = {
  frontend:  "bg-cyan-400",
  backend:   "bg-green-400",
  baseDatos: "bg-indigo-400",
  herramientas: "bg-orange-400",
}

// Lista de tecnologías con icono oficial, colores de marca y categoría
export const tecnologias = [
  {
    id: 1,
    nombre: "JavaScript",
    categoria: "frontend",
    fondo: "#F7DF1E",
    colorIcono: "#323330",
    degradado: "from-yellow-400/25 to-amber-300/25",
    Icono: SiJavascript,
  },
  {
    id: 2,
    nombre: "React",
    categoria: "frontend",
    fondo: "#20232A",
    colorIcono: "#61DAFB",
    degradado: "from-cyan-400/25 to-blue-500/25",
    Icono: SiReact,
  },
  {
    id: 3,
    nombre: "HTML5",
    categoria: "frontend",
    fondo: "#E34F26",
    colorIcono: "#ffffff",
    degradado: "from-orange-500/25 to-red-400/25",
    Icono: SiHtml5,
  },
  {
    id: 4,
    nombre: "CSS3",
    categoria: "frontend",
    fondo: "#1572B6",
    colorIcono: "#ffffff",
    degradado: "from-blue-500/25 to-sky-400/25",
    Icono: SiCss,
  },
  {
    id: 5,
    nombre: "Node.js",
    categoria: "backend",
    fondo: "#339933",
    colorIcono: "#ffffff",
    degradado: "from-green-500/25 to-emerald-400/25",
    Icono: SiNodedotjs,
  },
  {
    id: 6,
    nombre: "Express",
    categoria: "backend",
    fondo: "#353535",
    colorIcono: "#ffffff",
    degradado: "from-neutral-400/25 to-stone-500/25",
    Icono: SiExpress,
  },
  {
    id: 7,
    nombre: "MySQL",
    categoria: "baseDatos",
    fondo: "#4479A1",
    colorIcono: "#ffffff",
    degradado: "from-blue-600/25 to-cyan-500/25",
    Icono: SiMysql,
  },
  {
    id: 8,
    nombre: "SQLite",
    categoria: "baseDatos",
    fondo: "#003B57",
    colorIcono: "#7DC8E7",
    degradado: "from-sky-700/25 to-blue-800/25",
    Icono: SiSqlite,
  },
  {
    id: 9,
    nombre: "Prisma",
    categoria: "baseDatos",
    fondo: "#0D1117",
    colorIcono: "#5C7CFA",
    degradado: "from-indigo-600/25 to-purple-500/25",
    Icono: SiPrisma,
  },
  {
    id: 10,
    nombre: "Git",
    categoria: "herramientas",
    fondo: "#F05032",
    colorIcono: "#ffffff",
    degradado: "from-red-500/25 to-orange-400/25",
    Icono: SiGit,
  },
  {
    id: 11,
    nombre: "GitHub",
    categoria: "herramientas",
    fondo: "#24292F",
    colorIcono: "#ffffff",
    degradado: "from-neutral-600/25 to-slate-600/25",
    Icono: SiGithub,
  },
  {
    id: 12,
    nombre: "Python",
    categoria: "backend",
    fondo: "#3776AB",
    colorIcono: "#FFD43B",
    degradado: "from-blue-500/25 to-yellow-400/25",
    Icono: SiPython,
  },
  {
    id: 13,
    nombre: "Next.js",
    categoria: "frontend",
    fondo: "#000000",
    colorIcono: "#ffffff",
    degradado: "from-neutral-700/25 to-slate-600/25",
    Icono: SiNextdotjs,
  },
  {
    id: 14,
    nombre: "Tailwind CSS",
    categoria: "frontend",
    fondo: "#0EA5E9",
    colorIcono: "#ffffff",
    degradado: "from-sky-400/25 to-cyan-500/25",
    Icono: SiTailwindcss,
  },
]
